### ISSUE TITLE
DA (arc) record type not supported

### ISSUE THREAD

**Issue by sbrodehl** [dbrgn/airspace-visualizer#46]
Hi there,

I needed to adjust an AC Q for a local competition and was lucky enough to find the airspace visualizer to check the changes. I really like the tool, modern look and very easy to use ;-)

But it looks like the DA (arc) record type is not supported, I am not sure if the parsing is not working, or the visualisation of the arc.

Here is the definition of the DA record type:
```
DA radius, angleStart, angleEnd    ; add an arc, angles in degrees, radius in nm (set center using V X=...)
```

Unfortunately, the example file from [Switzerland](https://raw.githubusercontent.com/dbrgn/openair-rs/master/example_data/Switzerland.txt) does not contain a single DA record type, but the [format website](http://www.winpilot.com/UsersGuide/UserAirspace.asp) shows the following example:

```
* Reno Class C
AC C
AN RENO
AL 7200 ft
AH 8400 ft
* this item will have 3 labels
AT 39:36.8 N 119:46.1W
AT 39:22.8 N 119:45.1W
AT 39:29.9 N 119:36.1W
V X=39:29.9 N 119:46.1W
DA 10,270,290
DA 7,290,320
DA 10,320,200
V D=-
DA 5,200,270
```

I was able to get a visualisation with another tool, but would like to use this one!
Please let me know if I can help in any way!

**Comment by sbrodehl** [comment]
Here is the log of the website using the Reno Class C airspace above.

```javascript
index.ts:170 Loading file... File {name: 'Reno_Class_C.txt', lastModified: 1700237339764, lastModifiedDate: Fri Nov 17 2023 17:08:59 GMT+0100 (Central European Standard Time), webkitRelativePath: '', size: 233, …}
airspace_visualizer_bg.js:148 process_openair (233 bytes)
airspace_visualizer_bg.js:152 Finish Some("RENO")
index.ts:178 Data returned by WASM: [{…}]
leaflet-src.js:3260 Uncaught Error: Bounds are not valid.
    at NewClass.fitBounds (leaflet-src.js:3260:1)
    at reader.onload (index.ts:212:21)
fitBounds @ leaflet-src.js:3260
reader.onload @ index.ts:212
load (async)
loadFile @ index.ts:172
onDrop @ drag_drop.ts:32
```

**Comment by dbrgn** [comment]
Hm, if I remember correctly, the "geom" field should contain GeoJSON that is passed directly to leaflet. Something about the geometry seems to be invalid, or at least Leaflet doesn't want to render it...

**Comment by sbrodehl** [comment]
According to the GeoJSON spec the type `ArcSegment` is unknown, and for the type `Polygon` a  `coordinates` member is required (with a list of coordinates, not a list of segments).
So the `geom` field is not valid GeoJSON.

**Comment by dbrgn** [comment]
Ah, you're right, it's not GeoJSON. Right now arc support simply isn't implemented yet. I'll give it a look!

**Comment by dbrgn** [comment]
Ok, so the gist is:

- Arcs are not directly supported by Leaflet.js
- We can approximate them by using arc.js, but that is ugly
- Instead, we could use a D3 plugin, something like this (suggestion by ChatGPT, untested):

```js
  var map = L.map('map').setView([0, 0], 2);

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors'
  }).addTo(map);

  // Define the center of the arc and its radius
  var arcCenter = L.latLng(0, 0);
  var arcRadius = 5;

  // Create SVG overlay using Leaflet.D3SvgOverlay
  L.d3SvgOverlay(function(selection, projection) {
    // Use D3.js to draw a polygon with an arc
    var arcGenerator = d3.arc()
      .innerRadius(0)
      .outerRadius(arcRadius * projection.scale)
      .startAngle(Math.PI / 4) // Adjust start angle
      .endAngle(3 * Math.PI / 4); // Adjust end angle

    var polygon = selection.append('polygon')
      .attr('points', arcGenerator.centroid())
      .attr('fill', 'red');

    // Reposition the polygon based on the center coordinates
    var transform = d3.geoTransform({ point: function(x, y) {
      var point = projection([arcCenter.lng, arcCenter.lat]);
      this.stream.point(point[0], point[1]);
    }});
    polygon.attr('transform', d3.geoTransform({point: transform}));

  }).addTo(map);
```

Today I spent the whole afternoon updating the build system deps (#47). Additionally, there's still a pretty bad issue open (drag&drop seems broken on Chromium based browsers, see #34) that should be fixed first.

I do think this is an interesting problem, but I can't say when I'll find time to work on it. If you (or someone else) would give it a try, a PR would be very welcome!

**Comment by sbrodehl** [comment]
Hi there,

I looked into the code a bit more and as far as I understand each airspace is represented as a [polygon (with event listeners)](https://github.com/dbrgn/airspace-visualizer/blob/abc1b8ab81a93ff56b6edf19f4f28f2ab50d1bc1/www/index.ts#L135). Currently, it is assumed that the geometry only consists of segments of points, which easily form a polygon. But in fact, a segment can also be an arc, which needs to be joined with all the other segments in the geometry.

I actually dont know enough about how the D3 arc generator polygon can be extended with more points or segments/polygons to form the complete geometry, but will look into it next week I hope.

**Comment by dbrgn** [comment]
I started looking at this again today. And from how I understand the OpenAir format, this is defined in an incredibly stupid way.

    DA radius, angleStart, angleEnd    ; add an arc, angles in degrees, radius in nm (set center using V X=...)

So this means that there is a centerpoint and a radius. However, what should happen if the centerpoint isn't actually `radius` nautical miles away from the start?

Maybe the answer is "it must be", but someone sent me an airspace via e-mail where the DB arc type is used. In the DB type, the arc is defined using start, end and centerpoint. However, in one of the two arcs in that airspace, the distance [start, centerpoint] and [centerpoint, end] differs by more than 250m when calculating actual distance in meters with the curvature of earth / map projection taken into account. I thought, maybe it's not about actual distance, but just about lat/lng delta (using pythagoras)? But even then the distances differ significantly.

I wonder where that weird format is coming from... Do NOTAMs specify airspaces using arcs?

My next step is to try to contact some manufacturers that actually render those files on variometers to find out if there is a sane intepretation of that format. If there isn't, then files using arcs should throw an error.

**Comment by sbrodehl** [comment]
Hi there!

Thanks for getting back to the issue. There are two ways to define arcs in open air:
* __DA radius, angleStart, angleEnd__    ; add an arc, angles in degrees, radius in nm (set center using V X=...)
* __DB coordinate1, coordinate2__         ; add an arc, from coordinate1 to coordinate2 (set center using V X=...)

__DA__ defines the arc via the radius and the start and end angle. The center point is set with __V X=...__. The angles are taken from a compass rose (with 0° being top/north, 90° right/east, ...). In this setting all points on the arc must be computed, therefore all points will have the correct distance (per definition).

__DB__ is another story: Here two points from the arc are set as the start and end points. Since the center point is also set with __V X=...__ it is quite likely that the arc is not possible to construct, and/or nurmerical deviations lead to unplausible geometries. IMHO start and end must be the same distance from the center (as per definition! - otherwise they are not on the same arc).
The be fair, I have not seen __DB__ in use.

One reason your calculations might be off is the used projection? If I remember correctly ICAO uses Lambert conformal conic (LCC) projection, except for poles, there something else is used (can't remember).

Regarding NOTAMs: Often the airspaces are specified as line segments (polygons) - it is probably easier to use!

What projection do you use in your calculations?
Is the error you see dependent on the latitude?
Whats the source of the airspace (which includes the DB arc)? Maybe someone just hacked together some points and did not check for correctness?
